import Head from "next/head";
import styles from "../styles/home.module.scss";

import { Poppins } from "next/font/google";

const poppins = Poppins({
   weight: ["400", "500", "700", "900"],
   preload: false,
});

export default function Home() {
   return (
      <>
         <Head>
            <title>Apaixonado por tecnologia - Sujeito Programador</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={`${poppins.className} ${styles.container}`}>
            <div className={styles.containerHeader}>
               <section className={styles.ctaText}>
                  <h1>Levando você ao próximo nível</h1>
                  <span>
                     Uma plataforma com cursos que vão do zero até o
                     profissional na pratica, direto ao ponto aplicando o que
                     usamos no mercado de trabalho. 👊
                  </span>
                  <a>
                     <button>Começar Agora!</button>
                  </a>
               </section>
               <img src="/images/banner-conteudos.png" alt="conteudos" />
            </div>
            <hr className={styles.divisor} />

            <div className={styles.sectionContent}>
               <section>
                  <h2>Aprenda criar aplicativos para Android e iOS</h2>
                  <span>
                     Você vai descobrir o jeito mais moderno de desenvolver apps
                     nativos para iOS e Android, construindo aplicativos do zero
                     até aplicativos.
                  </span>
               </section>

               <img
                  src="/images/financasApp.png"
                  alt="Conteúdos desenvolvimento de apps"
               />
            </div>

            <hr className={styles.divisor} />

            <div className={styles.sectionContent}>
               <img
                  src="/images/webDev.png"
                  alt="Conteúdos desenvolvimento de aplicacoes web"
               />

               <section>
                  <h2>Aprenda criar sistemas web</h2>
                  <span>
                     Criar sistemas web, sites usando as tecnologias mais
                     modernas e requisitadas pelo mercado.
                  </span>
               </section>
            </div>
         </main>
      </>
   );
}
