import Head from "next/head";

import { Poppins } from "next/font/google";

const poppins = Poppins({
   weight: ["400", "500", "700", "900"],
   preload: false,
});

export default function Home() {
   return (
      <>
         <Head>
            <title>Sistema Institucional</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={`${poppins.className}`}>
            <div>
               <h1>Denis Moreira</h1>
            </div>
         </main>
      </>
   );
}
